# Generated by Django 4.2.5 on 2023-10-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursesName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('is_puplish', models.BooleanField()),
                ('cateoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('coursesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.courses')),
            ],
        ),
    ]
